### PR TITLE
Remove search_srdb function

### LINKED ISSUE #11: Remove search_srdb?
Hey @stephpenn1 about the initial setup work you did with the `search_srdb()` function—I see where you were going and like it. Great initial commenting, log messaging, use of `grepl`. You were pursuing a solid strategy and taking a really robust programming approach. So 👏 

However, all that said...do you think we'll still need it, given how the code has developed subsequently? I'm not sure, but if not, it would be good to remove that 'dead code' from the Rmd.

### PR DESCRIPTION
**Pull request by stephpenn1**
Closes #11

### CODE REVIEW

**Comment by stephpenn1** [comment]
@bpbond what is happen in these tests to make them fail?

**Comment by bpbond** [comment]
That's me f***ing up—I will try to fix. Right now the test fails for EVERYTHING 😞 . Happy to go over in more detail if you're interested in learning, but otherwise, hold tight! Thx.

**Comment by stephpenn1** [comment]
@bpbond how should I start debugging this failed test?

**Comment by bpbond** [comment]
@stephpenn1 Start by resolving the conflict in the Rmd file—that should be the only problem.

**Comment by bpbond** [comment]
Happy to walk through this w/u if useful.

**Pull request merged**
